### ISSUE TITLE
problem executing

### ISSUE THREAD

**Issue by Warfenix** [SnakePin/Yet-Another-Zoom-Autojoin-Bot-CSharp#1]
when I send the path of the .csv file
this shows me the message:

Zoom autojoin bot by SnakePin, this time made with .NET!
Version: 0.0.1
Enter CSV file path:
C: \ Users \ **** \ Desktop \ book12.csv
Fully loaded and initialized.

but after this, the time comes when I try to perform the test but it does not run
any ideas?

**Comment by snake-4** [comment]
If you don't get any messages on the console either, I'd like to see your .csv file as it might be wrongly formatted.

**Comment by Warfenix** [comment]
here is the file I used as a test:
https://gofile.io/d/2C8A4i

**Comment by snake-4** [comment]
Please use the latest version and you forgot to add the header line `dayOfWeek,timeIn24H,meetingId,meetingPsw,meetingTimeInSeconds,comment`. This text must be at the first line.

**Comment by Warfenix** [comment]
ok, I have updated the version and the csv file and this is the error that occurs now:

https://prnt.sc/vjhrbi

I don't know what it will be, but I was checking my version of .net framework with:
  https://github.com/EliteLoser/DotNetVersionLister

but I don't really understand if I have 3.5 installed
this is the output:

> ComputerName: localhost
>> = 4.x: 4.8 or later
>v4 \ Client: Installed
>v4 \ Full: Installed
>v3.5: Installed
>v3.0: Installed
>v2.0.50727: Installed
>v1.1.4322: Not installed (no key)
>Ping: True
>Error        :

any ideas?

**Comment by snake-4** [comment]
One of the `timeIn24H` parameters is wrong, make sure it has a zero in front like this `09:00` and not like this `9:00`.

**Comment by Warfenix** [comment]
ok i changed what you said, and now it recognizes the csv file correctly, but now this is the error i get:

> Fully loaded and initialized.
Joining a session. ID: 4133749272 Password: 123 MeetingTimeInSeconds: 3600
Main menu couldn't be found or interacted with. Exception: System.AggregateException: Se han producido uno o varios errores. ---> System.AggregateException: Se han producido uno o varios errores. ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en YAZABNET.Utils.<>c__DisplayClass4_0.<ClickButtonInWindowByText>b__1()
   en YAZABNET.Utils.<>c__DisplayClass2_0.<<DidPredicateBecomeTrueWithinTimeout>b__0>d.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en YAZABNET.Utils.<DidPredicateBecomeTrueWithinTimeout>d__2.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   en YAZABNET.Utils.ClickButtonInWindowByText(Window window, String text)
   en YAZABNET.ZoomAutomationFunctions.OpenZoomJoinMenu(AutomationBase automation)
   en YAZABNET.ZoomAutomationFunctions.JoinZoom(String meetingID, String meetingPSW)
---> (Nº de excepción interna 0) System.AggregateException: Se han producido uno o varios errores. ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en YAZABNET.Utils.<>c__DisplayClass4_0.<ClickButtonInWindowByText>b__1()
   en YAZABNET.Utils.<>c__DisplayClass2_0.<<DidPredicateBecomeTrueWithinTimeout>b__0>d.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en YAZABNET.Utils.<DidPredicateBecomeTrueWithinTimeout>d__2.MoveNext()
---> (Nº de excepción interna 0) System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en YAZABNET.Utils.<>c__DisplayClass4_0.<ClickButtonInWindowByText>b__1()
   en YAZABNET.Utils.<>c__DisplayClass2_0.<<DidPredicateBecomeTrueWithinTimeout>b__0>d.MoveNext()<---
<---



starts the zoom application, but does not join the meeting, just leaves the zoom application open
any ideas?
btw thanks for trying to help: u

**Comment by snake-4** [comment]
Hm, can you try this one please https://github.com/SnakePin/Yet-Another-Zoom-Autojoin-Bot-CSharp/releases/download/0.0.3/Release.zip and if that doesn't work either, can you please give me your Discord account if you have one?

**Comment by Warfenix** [comment]
it's not working bro either.
my discord is warfenix # 3866
:u
